spring:
  profiles:
    active: dev


#º§ªÓ≈‰÷√∑Ω Ω
#  spring.profiles.active=dev|prod|test
#  java -jar tuling-vip-springboot-02-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
#-Dspring:profiles:active=dev|prod|test: